### ISSUE TITLE
Missing checksums.txt.sig in 0.22.0

### ISSUE THREAD

**Issue by vync-SB** [terraform-linters/tflint#1006]
Hi,

I am wondering if removing the checksums signature verification file from the 0.22.0 release assets was intentional. 

This has left me with a broken signature verification step as in the following extract from a Dockerfile:
```
RUN [ "/bin/sh", "-c", "TFLINT_VERSION=$(curl --silent \"https://api.github.com/repos/terraform-linters/tflint/releases/latest\" | grep '\"tag_name\":' | sed -E 's/.*\"([^\"]+)\".*/\\1/' ); echo ${TFLINT_VERSION} > ${workdirectory}/tflint_version.txt" ]

RUN [ "/bin/sh", "-c", "TFLINT_VERSION=$(cat ${workdirectory}/tflint_version.txt); os=$(cat ${workdirectory}/os.txt); gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys ${TFLINT_GPG_KEY} && status_code=$(curl -s -L --write-out \"%{http_code}\" -O https://github.com/wata727/tflint/releases/download/${TFLINT_VERSION}/tflint_${os}.zip) && echo \"Status code returned when downloading tflint is ${status_code}\" && [[ ${status_code} == 200 ]] && curl -s -L -O https://github.com/wata727/tflint/releases/download/${TFLINT_VERSION}/checksums.txt.sig && curl -s -L -O https://github.com/wata727/tflint/releases/download/${TFLINT_VERSION}/checksums.txt && gpg --verify checksums.txt.sig checksums.txt && sed -n -i -e \"/tflint_${os}/p\" checksums.txt && sha256sum -c checksums.txt && unzip tflint_${os}.zip && rm checksums.txt.sig && rm checksums.txt && rm tflint_${os}.zip && mv ${workdirectory}/tflint /usr/local/bin/ " ]
```
and these are the associated logs:
![image](https://user-images.githubusercontent.com/49639170/102600394-a8ae1900-4116-11eb-8593-faca0adbb1c2.png)

Please leave a comment

Thank you

**Comment by bendrucker** [comment]
@wata727 have you been handling this locally?

**Comment by wata727** [comment]
Ah, yes. I always sign the checksum locally and attach the signature to the release after completed GitHub Actions.
For v0.22.0, I just added the signature file.

I would like to consider automating the release, including signing, and clarifying the release process.

**Comment by vync-SB** [comment]
Thanks guys, I'll test this now again and close the issue if we are all set.
