### ISSUE TITLE
feature request: enforce terraform and providers fixed version

### ISSUE THREAD

**Issue by m00lecule** [terraform-linters/tflint#1051]
Hello Guys!

Nowadays code is shared between group of people that might had installed tools in different versions. This approach increases work entropy. For example it adds additional work when unnecessary change is shown by `terraform plan`. Checking terraform version in state bucket, that has been run lately might be reduced by forcing fixed version when defining `terraform` block.

TFlint is missing `fixed_version` parameter in `terraform_required_version` rule, that would evaluate following block as invalid:

```sh
terraform {
  required_version = ">= 0.12.6"

  required_providers {
    aws = ">= 2.41"
  }
}
```

forcing following configuration:

```sh
terraform {
  required_version = "=0.12.6"

  required_providers {
    aws = ">= 2.41"
  }
}
```

I believe this feature might by useful in typical CI workflow - providing strict information about requirements

**Comment by wata727** [comment]
Can dependency lock file or `tfenv` solve this problem?
https://www.terraform.io/docs/language/dependency-lock.html
https://github.com/tfutils/tfenv

**Comment by m00lecule** [comment]
@wata727 dependency lock file does not offer backward compatibility ( terrafrom < 0.14.0 ). On the other hand using `.terraform-version` might be misleading and break consistency - putting required version in two files makes our configuration redundant.

**Comment by m00lecule** [comment]
@wata727 Also I can imagine a situation, when we would like to force migration to particular terraform version.  For instance team could make a statement that we only use terraform in version `0.12.29` but after some breaking changes we would like to migrate to `0.13.5`. Typical CI workflow using `TFlint` would force this policy. Anyways I will go through source code and check if I am capable to implement this feature

**Comment by bendrucker** [comment]
Terraform is getting better at gracefully handling cross version usage. State files are usable by older versions, for example, since states have a version and the format is pretty stable. This was back-ported to 0.13.6 as well. 

There is definitely some room to add to this rule but I also want to echo the sentiment that we want to defer to Terraform's own recommended patterns wherever possible. Keeping up with Terraform's advances is hard enough as consequentially backwards compatibility is not a goal for the core Terraform rule set or TFLint in general.

**Comment by m00lecule** [comment]
@wata727, @bendrucker   - I just realized that fixing terraform version would be nightmare. For example when patch release would be available - it would require lots of work for migration.

But I was thinking of implementing this test in a bit different way - to verify if required version will match the constraints. 

For example 

```hcl
terraform {
  required_version = "= 0.12.6"

  required_providers {
    aws = "~> 2.0"
  }
}
```

should raise error when `terraform_aws_provider_branch` = `3.0` and `terraform_version` = `0.15` will be specified

and it will pass on following configuration
```hcl
terraform {
  required_version = ">= 0.12.6"

  required_providers {
    aws = "~> 3.0 " # or even ">= 2.0"
  }
}
```

It would unify the current provider branch and terraform version requirements

**Comment by bendrucker** [comment]
Don't understand what `terraform_provider_version`. Feel free to continue the discussion but as noted this isn't something we'll add.
