### ISSUE TITLE
Install plugins automatically

### ISSUE THREAD

**Issue by wata727** [terraform-linters/tflint#1067]
Currently, plugins must be manually installed in the directory, except for bundled plugins. However, to make it easier to customize with plugins, we need to improve the experience of plugin users.

I'm thinking of a mechanism that can automatically install the required plugins by providing commands such as `terraform init`. However, we can't have a registry like https://registry.terraform.io, so we'll have to think of another way.

Recently, I learned that Packer has a similar situation. The `packer init` automatically downloads and unpacks binaries that meet the naming convention from GitHub. Perhaps this implementation will be very helpful.
https://www.packer.io/docs/commands/init

**Comment by bendrucker** [comment]
Good find! Here's the package:

https://github.com/hashicorp/packer/tree/master/packer/plugin-getter

**Comment by bendrucker** [comment]
Seems like this was introduced quite recently, first commit to that package was 21 days ago.
