### ISSUE TITLE
rule to allow no resource blocks in IAC tf modules for apps

### ISSUE THREAD

**Issue by kumarvt** [terraform-linters/tflint#1097]
Most of my infra tf code is kept and maintained as modules in their own repositories, we are looking to find if there is a tflint  rule that we can use to report/fail on exceptions when application developers are pushing code to app repos in git whenever they have not used one of the pre-baked tf module and instead used resource block to provision resources. At the moment we do these checks manually i.e. scan for resource blocks in application tf code before we approve the PRs.

**Comment by bendrucker** [comment]
Hi, there's no existing rules like this. The `terraform` rule set covers documented Terraform best practices and style rules but not personal preferences like this. You're welcome to write a plugin!

https://github.com/terraform-linters/tflint-ruleset-template
