### ISSUE TITLE
Use tflint against terraform v0.12.x

### ISSUE THREAD

**Issue by prithakundu** [terraform-linters/tflint#1135]
I want to use tflint to lint terraform v0.12. I have installed older version of tflint 0.17.0 for that. But  there is no option of tflint --init to install plugins in version 0.17.0. How i need to install aws plugin for tflint 0.17.0? Also "source" and "version" keyword not supported inside plugin block for config file .tflint.hcl. Do we need to install plugins manually? if so what is the command.

**Comment by bendrucker** [comment]
Yep, TFLint uses Terraform as a library and is thus not strictly compatible with older configuration:

https://github.com/terraform-linters/tflint#do-i-need-to-install-terraform-for-tflint-to-work
https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/compatibility.md

The `--init` flag was added recently, you will have to download plugins to the appropriate directory yourself. This is clearly spelled out in the documentation for the version you're using:

https://github.com/terraform-linters/tflint/blob/v0.17.0/docs/guides/extend.md

Keep in mind that plugins operate similarly to Terraform and the SDK and plugin protocol go through breaking changes sometimes. TFLint's plugin interface is less stable than Terraform. You may also have to seek out older versions of plugins that are compatible with the older TFLint version.
