### ISSUE TITLE
Support output format compatible with sonarqube

### ISSUE THREAD

**Issue by sushant-pradhan** [terraform-linters/tflint#1136]
Sonarqube supports submitting generic issue types by passing it in a specific format: https://docs.sonarqube.org/latest/analysis/generic-issue/. The proposal is to allow passing/overriding output format by passing a flag say `--format sonar` and updating the json output in this case to the one expected by Sonar.

This will enable to view, assign and ensure terraform is also statically linted and pushed to Sonar like other programming languages.

**Comment by bendrucker** [comment]
Hi, this is something we'd consider a PR for but are unlikely to work on otherwise. I'm also not sure this is appropriate to even include in TFLint. For a proprietary format like this, I would suggest using TFLint's JSON output and then passing that to your own program that converts it into the output you need.

**Comment by sushant-pradhan** [comment]
I am ready to contribute provided if is an acceptable change. Let me know so that the PR effort will not go waste. Sonar being a opensource and a leader in static code analysis this additional feature will be more accepted IMO. I also verified the format hasn't changed since last LTS to current (7.9 to 8.9)

**Comment by bendrucker** [comment]
I don't think the case for TFLint including vendor specific formats is very strong. Are you sure SonarQube can't process an existing vendor-agnostic format like JUnit or checkstyle? These formats are widely used for rendering visual test outputs.

**Comment by sushant-pradhan** [comment]
Ok.. i will close the issue then. Thank you!
