### ISSUE TITLE
GPG Key 8CE69160EB3F2FE9 expired 

### ISSUE THREAD

**Issue by tvannahl** [terraform-linters/tflint#1157]
Hi,

the PGP/GPG Key provided in v0.30.0 is expired since 2019.

See: http://keyserver.ubuntu.com/pks/lookup?search=watassbass%40gmail.com&op=index

An upgrade would be nice to have.

**Comment by wata727** [comment]
Sent to keyserver.ubuntu.com

```
% gpg --keyserver hkp://keyserver.ubuntu.com --send-keys 8CE69160EB3F2FE9
gpg: sending key 131A2054C7B3FB65 to hkp://keyserver.ubuntu.com
```
