### ISSUE TITLE
Terraform parser errors should be reported in formatted outputs

### ISSUE THREAD

**Issue by bendrucker** [terraform-linters/tflint#1163]
When using the checkstyle or junit formatter, users may run TFLint with invalid, un-parseable configuration. Invalid configuration can result from subtle mistakes like typos (`variabl "foo" {}`) or errant quotes (`variable "foo" { type = "string" }`).

Currently, TFLint treats all errors that result from loading configuration as fatal and prints them and exits with a non-zero code. While this is still reasonably correct, users often do not understand the "Failed to load configurations" prefix and believe TFLint or specific rules to be broken. 

These errors are reported back with diagnostics and could be returned as JUnit or Checkstyle output. In cases where failure to load configuration does return diagnostics, we should pass them through.

**Comment by bendrucker** [comment]
See #1162 #983

**Comment by wata727** [comment]
Whether configuration errors should be treated as diagnostics is a difficult problem. If treated as a diagnostic, it is not obvious how to report errors that don't have line numbers or corresponding files.

Treating only line number-related errors as diagnostics is an option, but the criteria for determining whether it is a diagnostic or fatal error is a bit strange.

Also, in the future TFLint will no longer load configuration files in the same way as Terraform, making it more tolerant of schemas (e.g. `variabl" foo "{}` will not result in an error). That may alleviate the problem a bit.

**Comment by bendrucker** [comment]
Agree that it's tricky. My thought was to format diagnostics with associated ranges and in all other cases let those errors fall through and continue to be handled as they are now.

Relaxing the schema does help reduce the frequency/subtlety. It may still continue to be an issue for syntax errors (e.g. unclosed blocks).

**Comment by PatMyron** [comment]
> not obvious how to report errors that don't have line numbers

if needed, defaulting to line 1 in formats that require line numbers seems reasonable in cases where the actual line number is not obtainable

**Comment by bendrucker** [comment]
Is it even possible to not have a range associated? The errors in question would always arise from a specific issue in the user's TF config. 

An unreadable file comes to mind. And I'm not sure reporting obscure low level errors like that back via the chosen structured issue format makes clear sense.
