### ISSUE TITLE
Unable to download the docker image v0.30.0 from GH (access denied)

### ISSUE THREAD

**Issue by joselcaguilar** [terraform-linters/tflint#1170]
I cannot download the docker image from GH due to an issue with permissions:
```console
$ docker pull ghcr.io/terraform-linters/tflint:latest
Error response from daemon: Head https://ghcr.io/v2/terraform-linters/tflint/manifests/latest: denied: denied
```

## Version
```console
$ tflint -v
TFLint version 0.30.0
```

It's only working if we authenticate in docker CLI using a PAT 😌

**Comment by wata727** [comment]
Umm... I tried launching an EC2 instance and pulling it on the machine, but no error occurred.

**Comment by bendrucker** [comment]
Are you authenticating with `GITHUB_SECRET`? Would think it would work for public images but 🤷‍♂️.

**Comment by joselcaguilar** [comment]
@wata727 @bendrucker Thanks for your reply guys, I would like to avoid the GitHub auth using a PAT token with packages:read permissions for downloading.

In my case I execute the docker run directly in a CI/CD pipeline where we didn't need the PAT with Docker Hub, however, now it's needed with GH and we wanted to avoid store this in a vault or another credential manager as well as using the PAT in plain text.

Thanks in advance!

**Comment by bendrucker** [comment]
Ok, the part that's unclear is exactly what you're doing. Assuming this is a GitHub Actions workflow it would be helpful to share that. Seems unlikely that this is at all specific to TFLint and would apply to any public GH Container Registry image used in an Actions workflow.

**Comment by joselcaguilar** [comment]
I have tried again and it seems solved, maybe a exceptional GH disruption, thanks for your support @bendrucker @wata727 :)
