### ISSUE TITLE
Allow variables-xxx.tf and outputs-xxx.tf files for variables and outputs

### ISSUE THREAD

**Issue by BzSpi** [terraform-linters/tflint#1171]
Current Terraform naming recommendation for variables and outputs files is respectively `variables.tf` and `outputs.tf` files. It's also implemented this way in tflint rule `terraform_standard_module_structure`.

However, when dealing with big modules with submodules or when sharing similar features between modules, we may way to have variables and outputs in separates files for easier maintenance.

Modifying the `terraform_standard_module_structure` rule so that the variables files could be named `variables-xxx.tf`, and same thing for outputs would be a good compromise in my opinion.

I'd be glad to hear any opinion on this.

**Comment by bendrucker** [comment]
Go ahead and copy this rule out to a custom plugin if you'd like to add this logic. While that seems like a perfectly reasonable pattern, the job of the Terraform rule set is to enforce practices recommended by Terraform's own documentation. Introducing/encouraging new user land patterns is outside its scope.
