### ISSUE TITLE
Support controlling where install script installs tflint

### ISSUE THREAD

**Issue by williamboman** [terraform-linters/tflint#1179]
Hey! I'm looking at adding `tflint` to https://github.com/williamboman/nvim-lsp-installer, where I'd like to install `tflint` to a custom path. Currently it seems like the shell script is hard-coded to install `tflint` to `/bin/tflint`. I think it'd be pretty nice to control where it ends up installing the executable, for example via an environment variable `TFLINT_INSTALL_PATH`.

**Comment by bendrucker** [comment]
PR welcome! The install script is provided as a convenience, but accepting an install dir is reasonable. The official release data API for TFLint is the GitHub releases API. There are installer implementations other than the shell script, e.g., a Github Action:

https://github.com/terraform-linters/setup-tflint/blob/db27e99508f896b3c2a26580bbe3ef7df97d48c7/src/setup-tflint.js#L48-L51

> Currently it seems like the shell script is hard-coded to install tflint to /bin/tflint.

Only for Windows, normally `/usr/local/bin`

https://github.com/terraform-linters/tflint/blob/master/install_linux.sh#L67

**Comment by bendrucker** [comment]
Added in #1183

**Comment by williamboman** [comment]
Ah cool that was quick, thanks!!
