### ISSUE TITLE
Documentation: how to enable built-in rules?

### ISSUE THREAD

**Issue by andrewferrier** [terraform-linters/tflint#1190]
It appears that there are a variety of built-in rules for tflint: https://github.com/terraform-linters/tflint/tree/master/docs/rules. However, most of those don't appear to be triggering for my project. This is probably expected, because it looks as if most of them are disabled by default, but I don't see any documentation or examples on how to enable them, the configuration guide seems to just focus on plugins: https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/config.md.

It would be great to know how to turn these rules on.

**Comment by wata727** [comment]
See the `rule` blocks:
https://github.com/terraform-linters/tflint/blob/v0.31.0/docs/user-guide/config.md#rule-blocks

You can enable each rule like the following:

```hcl
rule "terraform_unused_declarations" {
  enabled = true
}
```

**Comment by andrewferrier** [comment]
Thanks!
