### ISSUE TITLE
Different versions with images, where should I pull form?

### ISSUE THREAD

**Issue by w0rmr1d3r** [terraform-linters/tflint#1193]
Hello!

First, thank you for your tool, it really is amazing 😄  !

Second, I'm using it by pulling it from DockerHub:
https://hub.docker.com/r/wata727/tflint
But the latest is `0.29.1`, 2 months old.
And in this repo I can see the `v0.31.0` already, 15 days old:
https://github.com/terraform-linters/tflint/pkgs/container/tflint/versions

Where should I pull the image from? Since the first one redirects me to this repo.

At the same time, I can't find any public AWS ECR repository to pull it from 😭 , I've searched for it, but found nothing.

thank you!

PS: times are checked when opening this PR, newer versions may appear.

**Comment by w0rmr1d3r** [comment]
I've looked for open and closed issues, found none regarding the problem I have.

Cheers!

**Comment by bendrucker** [comment]
See https://github.com/terraform-linters/tflint#docker, the image is now published to the GitHub container registry.

**Comment by bendrucker** [comment]
@wata727 I think you can edit the readme directly via DockerHub's web UI to add a link to the new image.

**Comment by w0rmr1d3r** [comment]
Thank you @bendrucker !

**Comment by wata727** [comment]
It makes sense. Updated
https://hub.docker.com/r/wata727/tflint
