### ISSUE TITLE
Allow location of plugins directory to be defined in the configuration file

### ISSUE THREAD

**Issue by tylert** [terraform-linters/tflint#1198]
The end of the plugins user guide https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md shows how to control the location of the plugins directory with an environment variable (`TFLINT_PLUGIN_DIR`).

It would be really swell to have this as a configuration item in the config file https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/config.md to allow this to be controlled on a per-project basis (since the `.tflint.hcl` file is likely to be checked into each git repo anyway).

**Comment by wata727** [comment]
I'm interested in your use case. Does this mean that you want to explicitly separate the plugin directories for each project? If so, why would you want to separate the directories?

**Comment by tylert** [comment]
The primary use-case would be a disposable build agent that doesn't have a traditional home directory.  Some of the terraform modules/projects I work with are already "opiniated" about where they store their local `.terraform*` files and .tflint would, ideally, be configurable using a similar mechanism in the `.tflint.hcl` file checked into each project.

If I have a long-lived config file, it would be nice to have a place to store config for where to instantiate the `.tflint*` rather than assume it should be plopped in my home directory.  While it is nice you have provided an environment variable for this purpose, it is difficult to provide this "help" to others working with this same "opinionated" terraform project/module.  It would then allow me to control, on a per-project basis through the project's `.tflint.hcl` file, which version of tflint and the rulesets I test/use for each module/project in the same directory where I also define the version of Terraform and Terraform providers I use with each project/module.

It would be very nice if I could ensure that a single `.tflint.hcl` file would have a single new parameter called something like `plugin_dir` which does the exact same thing as the `TFLINT_PLUGIN_DIR` environment variable does.

**Comment by wata727** [comment]
Thank you for explaining. It makes sense.

The only concern is how to handle relative paths. I guess that you probably want to specify a relative path from the project root directory. This is natural behavior if `.tflint.hcl` is in the same directory, but TFLint can read a config file in any directory with the `--config` flag. In this case, it may not be clear how the relative path should be resolved.

Absolute paths are easier in this regard, but I'm not sure if it's useful enough if you can only specify an absolute path.

**Comment by tylert** [comment]
Absolute paths might be ok for a lot of use cases as `$(git rev-parse --show-toplevel)` will automatically find the root of your git project.  It might be possible to template this into the config file using something like https://github.com/hairyhenderson/gomplate.

However, relative paths that contain no `..` would likely be my own personal preference.

I'm happy to help try out a custom build if you would like.

**Comment by bendrucker** [comment]
My expectation would be that a path in a config file is resolved relative to the file itself, with no restrictions on the content of that path. If the path is supplied directly to a program (e.g. via flags) then it's relative to the working directory.

**Comment by wata727** [comment]
There is already [`varfile`](https://github.com/terraform-linters/tflint/blob/v0.31.0/docs/user-guide/config.md#varfile) as an option to specify the path in the config file. I noticed that this is not a relative path to the file, but a relative path to the working directory.

Initially, I didn't consider this case, but for consistency, it might be a relative path to the working directory.

**Comment by bendrucker** [comment]
Interesting, I think there's a good case for resolving them differently, and just mentioning where relative paths are resolved in the docs. 

A `varfile` is a valid part of a Terraform configuration. It wouldn't make sense to have a TFLint config in your home dir that sets one. 

The plugin directory depends only on the TFLint config content. It's more likely that you'd want to configure a centralized plugin directory. 

If `~` is resolved to `$HOME` it seems fine to just resolve from the working dir for consistency too. If you have a home-level config and want a shared plugin directory you declare `plugin_dir = "~/.tflint/plugins"`.

**Comment by wata727** [comment]
Thank you for letting me your opinion. Hmmm, in the work I'm currently working on, `plugin_dir` was a higher priority design than `TFLINT_PLUGIN_DIR`. The idea is that the values explicitly declared by a config file take precedence over the settings given by the environment. This is the same idea as Terraform:
https://www.terraform.io/docs/language/values/variables.html#variable-definition-precedence

If the existing solution (`./.tflint.d/plugins`) meets your requirement, I'm thinking of closing this issue and #1235. What do you think?

**Comment by tylert** [comment]
I would definitely prefer the improvement you have proposed in https://github.com/terraform-linters/tflint/pull/1235 as opposed to the undocumented workaround suggested above.
