### ISSUE TITLE
Custom Modules

### ISSUE THREAD

**Issue by brianantonelli** [terraform-linters/tflint#121]
I see a way to exclude custom modules, but don't see any documentation on how to add custom modules/validations. I would like to add some custom validations for my custom Terraform provider and resources.. Is this possible?

**Comment by wata727** [comment]
Do you mean that you want to the plugin architecture for custom detectors?
Unfortunately, there is no such mechanism at the moment :(
Is "Terraform Validate" not satisfying your requirements?
https://github.com/elmundio87/terraform_validate

**Comment by brianantonelli** [comment]
Terraform Validate does somewhat meet our requirements; however, your framework is much more elegant. It's so much cleaner to define rules using HCL instead of relying on Python unit test cases. The output is also much cleaner! I definitely am looking forwarding to seeing custom modules, do you have any information or an ETA? 

Also, I noticed you tflint doesn't yet support STS. Is this something thats also on your radar, or something would accept a PR to support?

**Comment by wata727** [comment]
Umm... Unfortunately, I have no plans for the now. However, I feel that it is beneficial.
If you have an image of rule definition using HCL, please let me know.

> Also, I noticed TFLint doesn't yet support STS. Is this something thats also on your radar, or something would accept a PR to support?

I would like to increase the detectors of AWS resources more and more. Patches are welcome!

**Comment by howdoicomputer** [comment]
> plugin architecture for custom detectors

Very similar to https://github.com/wata727/tflint/issues/156

I have a need for detectors that are company specific that wouldn't be beneficial to the world at large. Detectors as plugins would solve that.

Looking at how detectors work, it would be entirely feasible to use [go-plugin](https://github.com/hashicorp/go-plugin) as a starting point for having a collection of detectors exposed via RPC from a binary. It might be worth looking into after the rewrite/refactoring is merged in and detectors are dropped in favor of rules.

**Comment by wata727** [comment]
Thanks for your advice. I think that plugin architecture should be needed to support other providers in the future.
However, there are many other problems that must be solved, so it will likely be a while later.

**Comment by howdoicomputer** [comment]
Yeah, I'm aware of the `next_tflint_dev` branch and am working off of that branch. Also, thank you for including inline documentation of the code base on that branch. Stuff like [this](https://github.com/wata727/tflint/blob/next_tflint_dev/tflint/runner.go#L42) is great.

**Comment by wata727** [comment]
An experimental plugin system has been released in v0.14. I will close this issue.
