### ISSUE TITLE
`terraform_module_pinned_source` treats a terraform repository (http) as a git ones when using GitLab.

### ISSUE THREAD

**Issue by bosmak** [terraform-linters/tflint#1226]
I had to disable the `terraform_module_pinned_source` since it recognizes GitLab terraform repositories as git ones.

As I started using GitLab and their terraform repository, I usually get my modules using something like this:

```hcl
module "module_name" {
  source  = "gitlab.com/<group>/<name>/<env>"
  version = "1.0.0"

  #parameters
}
```

But tflint always fails on the `terraform_module_pinned_source` check, I tried adding an `https://` at the start of the source code, and it didn't fail, I believe this happens because the GitLab URL starts with `git` mimicking the `git://` string.

## Version

```console
$ tflint -v
TFLint version 0.32.1
$ terraform -v
Terraform v1.0.3
```

**Comment by bendrucker** [comment]
Bit more specific/less hacky than that, the underlying HashiCorp library for parsing these URLs supports detecting GitLab URLs as git URLs in the same way Terraform handles `github.com/*`. However, Terraform itself doesn't enable that "detector," so I just needed to make TFLint match.
