### ISSUE TITLE
Standard module structure rule - required vs recommended

### ISSUE THREAD

**Issue by mveitas** [terraform-linters/tflint#1233]
The `terraform_standard_module_structure` rule currently has a requirement that all variables and outputs are placed into the corresponding files (variables in `variables.tf` and outputs into `outputs.tf`). The official Terraform documentation for the [module structure standards](https://www.terraform.io/docs/language/modules/develop/structure.html) states the following:

> Root module. This is the only required element for the standard module structure. Terraform files must exist in the root directory of the repository

> README. The root module and any nested modules should have README files.

> main.tf, variables.tf, outputs.tf. These are the recommended filenames for a minimal module, even if they're empty

> variables.tf and outputs.tf should contain the declarations for variables and outputs, respectively.

Outside of the first requirement, the rest are recommendations.

This rule should have a flag to be able to enable checking of variables within these files. In some cases for style and locality, it might be preferred to have outputs close to the resources/modules that are being referenced in the output.

## Version

v0.32.1

**Comment by bendrucker** [comment]
Not sure I agree. A given module either follows the standard structure or it doesn't. All of the recommendations are "should." If you prefer to put your variables or outputs somewhere else I don't think it's helpful to have empty files that suggest none are defined.

**Comment by bendrucker** [comment]
Also excessive configuration is something we want to avoid in these rules. At least an example of what configuration options you think would express your specific preferences would go a long way.
