### ISSUE TITLE
Disable all default rules

### ISSUE THREAD

**Issue by ninjahck** [terraform-linters/tflint#1256]
Is this possible to disable all rules except the one which are mentioned inside the .tflint.hcl file ?

**Comment by bendrucker** [comment]
Not currently

**Comment by ninjahck** [comment]
can we have this feature in the roadmap ?

**Comment by bendrucker** [comment]
There's no roadmap, this is a best effort volunteer project. You or someone else can submit a pull request. We leave issues open for ideas that seem valid but we can't make any specific commitments to working on things like this.

**Comment by wata727** [comment]
You can use the `disabled_by_default` option.
https://github.com/terraform-linters/tflint/blob/v0.35.0/docs/user-guide/config.md#disabled_by_default

**Comment by itstheceo** [comment]
> You can use the `disabled_by_default` option. https://github.com/terraform-linters/tflint/blob/v0.35.0/docs/user-guide/config.md#disabled_by_default

Unfortunately the it seems the `preset` has higher precedence than `disabled_by_default`, which means you cannot disable the `recommended` rules :( 

https://github.com/terraform-linters/tflint-ruleset-terraform/blob/main/docs/configuration.md
