### ISSUE TITLE
Failed to run Bump Homebrew Formula workflow

### ISSUE THREAD

**Issue by wata727** [terraform-linters/tflint#1285]
See https://github.com/terraform-linters/tflint/runs/4627551246?check_suite_focus=true

This issue will be fixed by https://github.com/mislav/bump-homebrew-formula-action/pull/27

**Comment by wata727** [comment]
Created PR to homebrew-core manually.
https://github.com/Homebrew/homebrew-core/pull/91991

**Comment by chenrui333** [comment]
👍

**Comment by wata727** [comment]
Confirmed the fix when v0.35.0 was released
