### ISSUE TITLE
No clear way to set attributes of rules via CLI

### ISSUE THREAD

**Issue by jo366** [terraform-linters/tflint#1307]
Trawled through the docs and cannot find a way to replicate this via cli arguments. is this even possible? 

```rule "terraform_module_pinned_source" {
  enabled = true
  style = "semver" 
}
```
A config file would not be appropriate as we run tflint as part of the pre-commit framework and our working directory will vary when we run git commit. Expecting us to cd to the root of each repository before we commit is not user friendly.

Expecting all of our developers to have the config file in their home directory is also not realistic as we would like to master this in code and perhaps have different config files per repo.

**Comment by bendrucker** [comment]
Not possible and not planned. Sounds like walking upwards looking for a config file would be viable. That has been discussed and would be a viable direction.
