### ISSUE TITLE
Please add a Linux Arm64 Docker image

### ISSUE THREAD

**Issue by mbyio** [terraform-linters/tflint#1323]
Currently if you want to run tflint in a Docker image on an M1 Mac, it works, but you have to use the emulator built into Docker, so it is really slow and it prints a warning saying you are running an image for the wrong platform. It would be nice if you produced a multi-platform Docker image that supports both Arm and x86.

**Comment by wata727** [comment]
See also https://github.com/terraform-linters/tflint/pull/1206

**Comment by wata727** [comment]
Released in v0.35.0.
https://github.com/terraform-linters/tflint/releases/tag/v0.35.0
