### ISSUE TITLE
Please add a way to force colors in the output

### ISSUE THREAD

**Issue by mbyio** [terraform-linters/tflint#1325]
We run tflint in a monorepo containing many terraform workspaces and modules. I want to run one invocation of tflint for each workspace and module. I use `find` to get paths to all the workspaces and modules, and then I use `parallel` to invoke tflint for each of them. However, when I use `parallel` to invoke `tflint`, I think `tflint` detects that it isn't a TTY, and it turns off colors. I actually want colors because it makes the output much easier to read, so I'd like to force enable them using a flag like `--color`.

**Comment by PatMyron** [comment]
related for reference: https://github.com/terraform-linters/tflint/pull/415
