### ISSUE TITLE
Add support for Terraform v1.2 syntax

### ISSUE THREAD

**Issue by lostplan** [terraform-linters/tflint#1388]
Changes: https://github.com/hashicorp/terraform/blob/v1.2/CHANGELOG.md

**Comment by joe-a-t** [comment]
Specific issues to call out where the linter fails include `precondition` and `postcondition` as well as [using variables in variable validation error messages](https://github.com/hashicorp/terraform/pull/30613)

**Comment by onematchfox** [comment]
Adding `replace_triggered_by` to the list please.
