### ISSUE TITLE
Compatibility with Terraform

### ISSUE THREAD

**Issue by jferreira23** [terraform-linters/tflint#1393]
Its possible make a matrix compatibility? Or just add the versions are supported on the [releases](https://github.com/terraform-linters/tflint/releases)? Is some confuse find a version of tflint to match with terraform version.

**Comment by wata727** [comment]
We can make a matrix, but currently only supports the latest version of TFLint, so it is not recommended to adopt the old TFLint for older Terraform versions.

Please see here for the description of compatibility in each version:
https://github.com/terraform-linters/tflint/blob/v0.36.2/docs/user-guide/compatibility.md
