### ISSUE TITLE
"This value is null, so it does not have any attributes." error from upstream module

### ISSUE THREAD

**Issue by spkane** [terraform-linters/tflint#1395]
I have an [upstream module](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/kubernetes-addons/helm-addon) that I am using which causes this error when linting.

```text
TFLint in _tf_modules/k8s/:

Failed to prepare rule checking; failed to eval an expression in .terraform/modules/k8s-addons/modules/kubernetes-addons/helm-addon/main.tf:67; Attempt to get attribute from null value: This value is null, so it does not have any attributes.
```

The module has this variable defined:

```hcl
variable "irsa_config" {
  type = object({
    kubernetes_namespace              = string
    create_kubernetes_namespace       = optional(bool)
    kubernetes_service_account        = string
    create_kubernetes_service_account = optional(bool)
    irsa_iam_policies                 = optional(list(string))
  })
  description = "Input configuration for IRSA module"
  default     = null
}
```

which is then referenced here:

```hcl
module "irsa" {
  count                             = var.irsa_config != null ? 1 : 0
  source                            = "../../irsa"
  create_kubernetes_namespace       = try(var.irsa_config.create_kubernetes_namespace, true)
  create_kubernetes_service_account = try(var.irsa_config.create_kubernetes_service_account, true)
  kubernetes_namespace              = var.irsa_config.kubernetes_namespace
  kubernetes_service_account        = var.irsa_config.kubernetes_service_account
  irsa_iam_policies                 = var.irsa_config.irsa_iam_policies
  addon_context                     = var.addon_context
}
```

and this generates the above error during linting. 

The terraform code works in general.

Is there a way to fix this in `tflint`, ignore this error, or ignore this specific module or file?

## Version

```console
$ tflint -v
TFLint version 0.36.2
+ ruleset.aws (0.13.4)

$ terraform -v
Terraform v1.2.1
on darwin_amd64
```

**Comment by wata727** [comment]
This error seems to make sense. I think this is because null is passed as an argument that should not be passed when calling the module (to be exact, the default value is used by omitting the argument). You probably get the same error when you run `terraform plan`.

**Comment by wata727** [comment]
Understood. In this case, I recommend removing the default value from the `irsa_config` variable. The default value is null, but obviously it's not supposed to use as null (it looks like a de facto required variable).

My recommendation is to fix the upstream module, but if it's difficult, I have no choice but to ignore inspection for the module.

**Comment by wata727** [comment]
I checked the module again, but it seems that the problem is that TFLint evaluates module arguments without considering the `count` argument.

I haven't confirmed the behavior, but Terraform may not evaluate arguments if the module's `count` is 0. In that case, TFLint should also be fixed to follow the semantics.

**Comment by spkane** [comment]
I have just tested this and indeed it appears to have solved the original issue. Thank you very much for getting this in!
