### ISSUE TITLE
[Question] What regex do I need to ignore a very specific folder in my repo, but NOT the underlying directories?

### ISSUE THREAD

**Issue by spkane** [terraform-linters/tflint#1396]
In this case, I need to ignore `environments/cluster-sandbox/`, but not the directories underneath it. That directory has an `*.auto.tfvars` file in it, which causes `tflint` to assume that it is a terraform directory, but in reality, that file is simply linked into some other locations lower down.

I tried a few regex approaches, but none of them seemed to work quite right.

Thanks!

**Comment by wata727** [comment]
TFLint only performs a check on the specified directory or file. So it does not have a mechanism to automatically recognize the Terraform directory.

You're probably running the check by a different script, so it's a good idea to review that.

**Comment by spkane** [comment]
Sorry about that. You are absolutely correct. I meant to post this in the `antonbabenko/pre-commit-terraform` repo.

**Comment by spkane** [comment]
https://github.com/antonbabenko/pre-commit-terraform/issues/391
