### ISSUE TITLE
Module Name 

### ISSUE THREAD

**Issue by anurodh-ti** [terraform-linters/tflint#1417]
Can we get present modules information while parsing through the terraform code through tflint?
We need to find for each resource in which module that resource is made because same resource name can be present in different modules.

**Comment by bendrucker** [comment]
Request is unclear, more info (eg examples) needed. TFLint module inspection already only emits issues tied to module variables and should report the attribute in a module call as the associated range in the code.

**Comment by anurodh-ti** [comment]
For each resource in a module, we are trying to map that resource with its AWS ID. Since different modules could have same resource name, for every AWS id we need both resource name and module in which that resource is present (this pair is unique).
Can tflint help us map for all modules present in terraform template, module names with all resources names that module has?

**Comment by sabhya-ti** [comment]
Hello. I am working alongside Anurodh (the guy that started the thread) in developing a custom plugin for TfLint. I hope to make you better understand the issue that we are facing together.
when tflint is called with --module (i.e. in module inspection mode)
then the list of resources obtained by runner.getResourceContent in the Check function [[link](https://github.com/sabhya-ti/plugin/blob/master/rules/aws_instance_example_type.go#L53)] may contain two resources [https://github.com/sabhya-ti/plugin/blob/master/terraformCode/module-1/main.tf#L1, https://github.com/sabhya-ti/plugin/blob/master/terraformCode/module-2/main.tf#L1] with the same terraform reference name ("showcase-1") in this case belonging to different modules [https://github.com/sabhya-ti/plugin/blob/master/terraformCode/main.tf#L67, https://github.com/sabhya-ti/plugin/blob/master/terraformCode/main.tf#L67]. My Check function needs to be able to distinguish between resources with the same terraform reference name from multiple modules, and I'm looking for a way to accomplish that.

// The functions below are not available in the check function and I'd like to know how else to accomplish that effect.
// resource.getModuleName() //should return "server-1" and "server-2" respectively if I run module inspection
// resrouce.getModulePath() //should give the path of the directory in which the resource under inspection is present

I hope I have been clear now. Thank you in advance for helping out.
