### ISSUE TITLE
unable to name container

### ISSUE THREAD

**Issue by RolfMoleman** [terraform-linters/tflint#1423]
## Introduction

neither `ghcr.io/terraform-linters/tflint:latest` or `ghcr.io/terraform-linters/tflint-bundle:latest`  support the use of the `--name` flag preventing naming of containers

## Expected Behavior

when passing the --name flag as part of docker run i would expect to be able to name the container. rather than be restriced to using the randomly generated names.

## Actual behavior

when running either `ghcr.io/terraform-linters/tflint:latest` or `ghcr.io/terraform-linters/tflint-bundle:latest` the response is consistently `Failed to parse CLI options; `name` is unknown option. Please run `tflint --help``

**Comment by bendrucker** [comment]
Moreover, container naming is not up to the container, there is nothing a container image could do to influence container engine configuration options like name.
