### ISSUE TITLE
Allow plugin version to be specified as SHA-1 hash

### ISSUE THREAD

**Issue by morancj** [terraform-linters/tflint#1486]
## Introduction

Allow plugin version to be specified as commit hash, as well as tag. Similar to pinning GitHub Actions versions to a commit.

## Proposal

For example, instead of

```hcl
plugin "aws" {
  enabled = true
  version = "0.16.0"
  source  = "github.com/terraform-linters/tflint-ruleset-aws"
}
```

I'd like to be able to use `version = "fa6372da4fafa89fdc1052d966742a070a716725"`.

```hcl
plugin "aws" {
  enabled = true
  version = "fa6372da4fafa89fdc1052d966742a070a716725"  # "0.16.0"
  source  = "github.com/terraform-linters/tflint-ruleset-aws"
}
```

## References

https://michaelheap.com/ensure-github-actions-pinned-sha/
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

**Comment by wata727** [comment]
Maybe we need a dependency lockfile like `terraform.lock.hcl`?

**Comment by wata727** [comment]
Opened https://github.com/terraform-linters/tflint/issues/1634 for the introduction of dependency lockfile. Closing this issue.
