### ISSUE TITLE
tflint-ignore multiple, but not all rules

### ISSUE THREAD

**Issue by sblask** [terraform-linters/tflint#1488]
## Introduction

I just ran into the situation where I want to ignore `terraform_standard_module_structure` and `terraform_naming_convention` on the same line, but the only way to do that at the moment is either ignore `all` which I don't want or this:

```
# tflint-ignore: terraform_naming_convention
variable "FOO_BAR" { # tflint-ignore: terraform_standard_module_structure
```
Which is ugly and limited to two rules.

## Proposal

It should be possible to ignore multiple rules like this:
```
# tflint-ignore: terraform_standard_module_structure,terraform_naming_convention,terraform_typed_variables
```
and/or do the same for a whole file like this:
```
# tflint-ignore-in-file: terraform_standard_module_structure
# tflint-ignore-in-file: terraform_naming_convention
# tflint-ignore-in-file: terraform_typed_variables
```
or this:
```
# tflint-ignore-in-file: terraform_standard_module_structure,terraform_naming_convention,terraform_typed_variables
```

**Comment by wata727** [comment]
Makes sense. You can change the `IsAffected()` behavior.
https://github.com/terraform-linters/tflint/blob/v0.39.3/tflint/annotation.go#L43-L57
