### ISSUE TITLE
Disable rule but still display / Force for specific rule

### ISSUE THREAD

**Issue by rgarrigue** [terraform-linters/tflint#1493]
## Introduction

I'm improving my TF code, setting up tflint being one step. It complains about using a default branch as ref. Understood, I want to ignore this warning as I'll fix it later while still working atm, but please don't hide it, because I'll forget. 

## Proposal

Either
- Force this rule, aka return code = 0 if only this (those) rule(s) fails
- Or ignore this rule, but still display the message

## Reference

ansible-lint got a skip_list (disable entirely) and warn_list (show warning but RC=0) https://ansible-lint.readthedocs.io/en/latest/rules/?highlight=skip-list#excluding-rules. Plus a `# noqa [rule-id]` to ignore an issue originating from a given commented line

**Comment by bendrucker** [comment]
I had a lot of trouble making sense of this request as written but it seems like existing features or already tracked issues cover the portions of this request that are viable.

* [Annotations](https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/annotations.md) allow you to ignore a specific line, for a single, all, or as of #1492 multiple rules. This is the most appropriate way to implement "I know this is a violation, but I'm ok with that." 
* [Customizing severity level](#715) for rules is tracked in an issue but not implemented
* "Or ignore this rule, but still display the message." Don't know what this means exactly but it doesn't sound like something we could consider. Disabling a rule means it's not invoked at all.
