### ISSUE TITLE
Impletent flag to return status code 0 on WARNINGs

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [terraform-linters/tflint#1555]
## Introduction

`tflint` has the `--force` flag to return status code zero during any issue. But I did not manage to suppress only WARNING status codes 2.
I need it in a pipeline to display any WARNINGs without failing the pipeline. However, I want the pipeline to fail on ERRORs only.

## Proposal

Add a flag to suppress WARNING status codes.

**Comment by bendrucker** [comment]
Closing in favor of a more generalized/complete proposal, #1556
