### ISSUE TITLE
Support any filename

### ISSUE THREAD

**Issue by sblask** [terraform-linters/tflint#1609]
## Introduction

I have Jinja template to generate Terraform code (which unfortunately is necessary because of Terraform limitations). It's called main.tf.j2 but I cannot use tflint on it: `File is not a target of Terraform`.  It's a pity because tflint is a tool for development and I can't use it directly on the file I am developing. I have to first generate my Terraform file before which makes the feedback loop longer.

## Proposal

Allow any filename when passed directly into tflint. If not that an alternative could be to allow reading from stdin like `terraform fmt` does.

**Comment by bendrucker** [comment]
Thanks for sharing, supporting calling TFLint on custom templates that will later become valid TF files is not something we plan to support.
