### ISSUE TITLE
Codeclimate output format

### ISSUE THREAD

**Issue by yushao2** [terraform-linters/tflint#1694]
## Introduction

Please introduce an output format that is compliant to codeclimate spec

https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types

This would benefit CI pipelines on gitlab as gitlab uses codeclimate format to perform code annotations. 

## Proposal
- Add new value for format `codeclimate`
- Add logic to support new output format

## References

https://docs.gitlab.com/ee/ci/testing/code_quality.html#implement-a-custom-tool

**Comment by yushao2** [comment]
@wata727 would you consider supporting a output just for gitlab, instead of for codeclimate as a whole?

I believe gitlab users would benefit greatly from having it natively supported

**Comment by bendrucker** [comment]
No, please read the existing thread:

https://github.com/terraform-linters/tflint/pull/1407#issuecomment-1145170443

There's a middle ground between nothing and TFLint taking on the burden of supporting a proprietary output format, and that's composing other tools to do the translation. #1407 alluded to `jq` but declined to share a snippet. A quick Google turns up https://www.npmjs.com/package/sarif-codeclimate. These may not be perfect drop-in fits for your exact use case but I'm confident that this problem is solved through composition. 

If you're a paying GitLab customer, tell them that SARIF support is important to you:

https://gitlab.com/gitlab-org/gitlab/-/issues/118496

**Comment by yushao2** [comment]
It's unfortunate that we have to compose other tools to do the translation, it feels like a hacky workaround for something that could be easily supported.

here's the script I wrote in python to do the translation for me

```
import json
import sys
import hashlib

def convert_to_codeclimate_json(tflint_json):
    gitlab_issues = []
    for issue in tflint_json['issues']:
        gitlab_issue = {}
        gitlab_issue['description'] = issue['message']
        gitlab_issue['fingerprint'] = hashlib.sha1(issue['message'].encode()).hexdigest()
        gitlab_issue['severity'] = 'minor'
        gitlab_issue['location'] = {}
        gitlab_issue['location']['path'] = issue['range']['filename']
        gitlab_issue['location']['lines'] = {}
        gitlab_issue['location']['lines']['begin'] = issue['range']['start']['line']
        gitlab_issues.append(gitlab_issue)
    return gitlab_issues

# Read TFLint output from stdin
tflint_output = sys.stdin.read()

# Parse TFLint output as JSON
tflint_json = json.loads(tflint_output)

# Convert to CodeClimate JSON format
codeclimate_json = convert_to_codeclimate_json(tflint_json)

# Write CodeClimate JSON output to stdout
json.dump(codeclimate_json, sys.stdout, indent=2)
```

usage: 
note that the python file is baked onto a container image with python and pylint set up
```yml
tflint:
  stage: quality
  image: <custom image>
  script:
    - tflint -f json | python /home/cicd/utils/json_to_gitlab_codeclimate.py > codeclimate_output.json
  artifacts:
    reports:
      codequality: codeclimate_output.json
```

**Comment by wata727** [comment]
Just as ESLint and RuboCop are supported by codeclimate-eslint and codeclimate-rubocop, codeclimate-tflint might be a help.
https://docs.gitlab.com/ee/ci/testing/code_quality.html#required-images
https://hub.docker.com/r/codeclimate/codeclimate-tflint

**Comment by bendrucker** [comment]
> It's unfortunate that we have to compose other tools to do the translation, it feels like a hacky workaround for something that could be easily supported.

Give this feedback to GitLab, a $7B company, and ask them to support SARIF. You won't find receptivity from volunteer maintainers with this attitude. 

Also relevant, found from a quick Google:

https://docs.codeclimate.com/docs/tflint
https://github.com/ST-Apps/codeclimate-tflint
