### ISSUE TITLE
Allow config file to be specified via TFLINT_CONFIG

### ISSUE THREAD

**Issue by joaocc** [terraform-linters/tflint#1828]
## Introduction
tflint already provides config settings as env variables. One that seems lacking is TFLINT_CONFIG, as an lower-priority option for the --config file.
If defined, TFLINT_CONFIG would be used in the same way as --config, unless --config is defined.

**Comment by bendrucker** [comment]
Existing:

https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/environment_variables.md

Would provide parity with:

https://developer.hashicorp.com/terraform/cli/config/environment-variables#tf_cli_config_file
