### ISSUE TITLE
Can't read existing varfile

### ISSUE THREAD

**Issue by synergiator** [terraform-linters/tflint#1900]
### Summary

With 0.48, I can't use parameters for varfile. 

### Command

tflint -var-file="terraform.tfvars"

### Terraform Configuration

```terraform
default, v. 1.6.3 on Debian 12
```

### TFLint Configuration

```HCL
plugin "terraform" {
  enabled = true
  preset  = "recommended"
}
```

### Output

```Shell
Failed to parse CLI options; `var-file=terraform.tfvars` is unknown option. Please run `tflint --help`
```

### TFLint Version

0.48.0

### Terraform Version

1.6.3

### Operating System

- [X] Linux
- [ ] macOS
- [ ] Windows

**Comment by bendrucker** [comment]
TFLint has always used POSIX-style variables, `--var-file` not `-var-file`. Please consult the docs before opening issues.

**Comment by synergiator** [comment]
sorry, indeed I've misread the docs!
