### ISSUE TITLE
The call-module-type option doesn't exist

### ISSUE THREAD

**Issue by raymondchen625** [terraform-linters/tflint#1935]
### Summary

When I run with option `--call-module-type=local`, I get error:
```
Failed to parse CLI options; `call-module-type` is unknown option. Please run `tflint --help`
```
My version is `0.49.0` on macOS and is installed with brew. Running `tflint --help`indeed doesn't show me the `--call-module-type` option. But if I build from the source, the options is there.

### Command

tflint --call-module-type=local

### Terraform Configuration

```terraform
n/a
```

### TFLint Configuration

```HCL
n/a
```

### Output

```Shell
Failed to parse CLI options; `call-module-type` is unknown option. Please run `tflint --help`
```

### TFLint Version

0.49.0

### Terraform Version

1.5.7

### Operating System

- [ ] Linux
- [X] macOS
- [ ] Windows

**Comment by bendrucker** [comment]
See https://github.com/terraform-linters/tflint/releases for the current release and its associated commit. The default branch is not immediately released.
