### ISSUE TITLE
String interpolation passed as a list

### ISSUE THREAD

**Issue by AlexcFrench** [terraform-linters/tflint#2008]
### Summary

When a module receives a single-item list, I believe the correct syntax is :-
private_endpoint_subresource_type = **["${var.private_endpoint_subresource_type}"]**

However, this fails with deprecated string interpolation error : 
Warning: [Fixable] Interpolation-only expressions are deprecated in Terraform v0.12.14 (terraform_deprecated_interpolation)

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.5.0/docs/rules/terraform_deprecated_interpolation.md

### Command

tflint

### Terraform Configuration

```terraform
passing a variable to a module that expects a list(string) type.
```

### TFLint Configuration

```HCL
default
```

### Output

```Shell
Warning: [Fixable] Interpolation-only expressions are deprecated in Terraform v0.12.14 (terraform_deprecated_interpolation)

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.5.0/docs/rules/terraform_deprecated_interpolation.md
```

### TFLint Version

0.50.3

### Terraform Version

1.7.5

### Operating System

- [ ] Linux
- [ ] macOS
- [X] Windows

**Comment by bendrucker** [comment]
> Interpolation-only expressions

Which is this: `"${foo}"`. Which you are doing, the list wrapping has no bearing on that. Each string in the list is itself an expression.

```tf
private_endpoint_subresource_type = [var.private_endpoint_subresource_type]
```
