### ISSUE TITLE
BUSL-1.1 licensed code found in tflint

### ISSUE THREAD

**Issue by johanneskastl** [terraform-linters/tflint#2050]
### Summary

During packaging tflint for openSUSE, we found that there are BUSL-1.1 licensed files included. Which means we can no longer package tflint.

```
BUSL-1.1: 8 files

    tflint-0.51.1/terraform/lang/funcs/filesystem.processed.go
    tflint-0.51.1/terraform/lang/funcs/filesystem_test.processed.go
    tflint-0.51.1/terraform/lang/funcs/sensitive.go
    tflint-0.51.1/terraform/lang/funcs/sensitive_test.go
    tflint-0.51.1/terraform/lang/funcs/terraform/functions.processed.go
    tflint-0.51.1/terraform/lang/funcs/terraform/functions_test.processed.go
    tflint-0.51.1/terraform/lang/functions.go
    tflint-0.51.1/terraform/lang/functions_test.processed.go
```

I found #2037 which mentions the licensing.

Could someone please clarify, which license tflint is now being released under?

Kind Regards,
Johannes

### Command

tflint

### Terraform Configuration

```terraform
none
```

### TFLint Configuration

```HCL
none
```

### Output

```Shell
none
```

### TFLint Version

0.51.1

### Terraform Version

none

### Operating System

- [X] Linux
- [ ] macOS
- [ ] Windows

**Comment by bendrucker** [comment]
This is already well-documented in the readme:

https://github.com/terraform-linters/tflint?tab=readme-ov-file#license

**Comment by johanneskastl** [comment]
Thanks for the quick clarification. I had missed the README, sorry. Sad, but we will have to drop tflint from the distribution.

Anyways, keep up the good work!

P.S.: IANAL, but GitHub shows `MPL-2.0, Unknown licenses found `, so apparently it gets confused by two license files. You might want to fix that...
