### ISSUE TITLE
Add source Attribute to Checkstyle Format

### ISSUE THREAD

**Issue by nyamada100** [terraform-linters/tflint#2056]
## Introduction

When using reviewdog to read tflint's checkstyle format output, the rule IDs from tflint are not displayed.

## Proposal

reviewdog refers to the source attribute when reading the checkstyle format, but the source attribute is missing in tflint's checkstyle format.

Please add the source attribute to tflint's checkstyle format output. For example, the content of the Rule attribute could be used as the source.

## References

https://github.com/reviewdog/reviewdog/blob/master/parser/checkstyle.go,
https://github.com/reviewdog/action-tflint/issues/87

**Comment by wata727** [comment]
Indeed, it seems that Checkstyle's XML output requires the `source` attribute.
https://github.com/checkstyle/checkstyle/blob/a7042e5119e6df9b8f782751af6cae2ee54a215a/src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java#L205-L224

Based on past history, there seems to be no reason to use the `rule` attribute, so this proposal seems reasonable.
https://github.com/terraform-linters/tflint/pull/82
https://github.com/terraform-linters/tflint/pull/122
