### ISSUE TITLE
Feature request: Detect unused variables

### ISSUE THREAD

**Issue by bitdivine** [terraform-linters/tflint#256]
I noticed that when I removed a variable from a terraform template, there was no warning that the variable supplied in the corresponding `data "template_file" "XXX" {` was unused.  By extension there was also no warning that the `data` section used to generate that template variable was also unused.

Detecting unused variables, locals and data would be a nice addition to tflint.

**Comment by bendrucker** [comment]
This was released in #739!

https://github.com/terraform-linters/tflint/blob/master/docs/rules/terraform_unused_declarations.md
