### ISSUE TITLE
Add --loglevel option

### ISSUE THREAD

**Issue by abitrolly** [terraform-linters/tflint#472]
`tflint` is too silent by default. I noticed `log.Printf("[DEBUG]` statements in the code and then found `TFLINT_LOG=debug tflint` on the main page. It would be convenient to transform this to an option, such as `tflint --loglevel=debug` or `tflint --loglevel=4`.

TFLint v0.12.0

**Comment by wata727** [comment]
This behavior is the same as Terraform.
https://www.terraform.io/docs/internals/debugging.html

Initially, I thought that the same behavior as Terraform can provide an easy-to-understand interface for Terraform users, but it is worth considering if there are many users who want the `--loglevel` option.

**Comment by karanrn** [comment]
Can I work on this?

**Comment by mikemaccana** [comment]
Came here for the same reason - failures on command line tools are generally logged with more than an exit code. Not logging errors might the same as Terraform, but it's definitely inconsistent with other Unix tools.
