### ISSUE TITLE
Add a check that modules are pinned to semantic versions

### ISSUE THREAD

**Issue by alexwlchan** [terraform-linters/tflint#513]
terraform_module_pinned_source does some checks that a module source isn’t ambiguous, but it could be stronger.

Terraform encourages us to use semantic versioning, right? So how about this check:

**Warn if a module is not pinned to a semantic version vX.Y.Z.**

This is stronger than the existing rule:

* Covers all module sources (except local path)
* Avoids ambiguous references in Git/Mercurial. Pinning to a non-default branch will pass the existing check, but might still be ambiguous.
* Gets easier to reason about references. I can use a commit hash as an unambiguous Git ref (`?ref=0ad21e6`), but it’s hard to know if that’s current or outdated. Forcing me to use a semver references fixes that.

The latter reason is my primary interest in the feature.

I’d be happy to have a first attempt at this, if you think it’s a good idea.

If so, do you think it should be a new rule, or a change to the existing rule?

**Comment by wata727** [comment]
Hi @alexwlchan. Thank you for opening the issue.

That makes sense. On the other hand, we may have to consider the case where you cannot use the semantic version for a module (e.g. untagged module).

Based on the above, it is good to create it as another rule or add a new option for `terraform_module_pinned_source` rule. There is currently no way to define per-rule options, so it might be a good idea to create a new rule.

**Comment by alexwlchan** [comment]
Having another rule sounds good (and maybe not one that’s on by default). 👍

I’ll have a play over the weekend and let you know how I get on.
