### ISSUE TITLE
Share GPG public key for release signing

### ISSUE THREAD

**Issue by TimJDFletcher** [terraform-linters/tflint#561]
In issue #252 you enabled signing of releases, please could you publish the public part of key that you are using to sign the releases.

To export the key use the following command:

```bash 
gpg --armor --export 8CE69160EB3F2FE9 > 8CE69160EB3F2FE9.key
```
Then commit and add the key to the tflint github repo.

**Comment by wata727** [comment]
Hi @TimJDFletcher, I already published my public key to a keyserver. I think you can get it with the following command, is that not enough?

```
% gpg --search-keys 8CE69160EB3F2FE9
gpg: data source: https://209.244.105.201:443
(1)     Kazuma Watanabe <watassbass@gmail.com>
          4096 bit RSA key 131A2054C7B3FB65, created: 2019-05-25, expires: 2021-05-24
```

**Comment by TimJDFletcher** [comment]
It sure if you know but the gpg keyserver network has been under attack for a while and is very unreliable. 

We have tested a few key servers and failed to find you key on them, it would I think be better to have the key published in repo. 

More info about the attack can be found here: https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f

**Comment by wata727** [comment]
Thanks for the explanation. That makes sense.
The public key has been added to the repository. Please let me know if anything is missing. Thank you again!

**Comment by TimJDFletcher** [comment]
In case this helps in the future this is how we are installing tflint in a Dockerfile with checksum validation via GPG.

```Dockerfile
# Install TFLint
COPY tflint.key tflint.key
RUN gpg --import tflint.key

ENV TFLINT_VERSION="v0.13.3"
ENV TFLINT_BASE_URL="https://github.com/terraform-linters/tflint/releases/download" \
    TFLINT_FILE_NAME="tflint_linux_amd64.zip" \
    TFLINT_CHECKSUM_FILE_NAME="checksums.txt"

RUN echo "Downloading TFLint from: ${TFLINT_BASE_URL}/${TFLINT_VERSION}/${TFLINT_FILE_NAME}" \
    && curl -fOL ${TFLINT_BASE_URL}/${TFLINT_VERSION}/${TFLINT_FILE_NAME} \
    && curl -fOL ${TFLINT_BASE_URL}/${TFLINT_VERSION}/${TFLINT_CHECKSUM_FILE_NAME} \
    && curl -fOL ${TFLINT_BASE_URL}/${TFLINT_VERSION}/${TFLINT_CHECKSUM_FILE_NAME}.sig \
    && gpg --verify ${TFLINT_CHECKSUM_FILE_NAME}.sig ${TFLINT_CHECKSUM_FILE_NAME} \
    && sha256sum --ignore-missing -c ${TFLINT_CHECKSUM_FILE_NAME} \
    && unzip ${TFLINT_FILE_NAME} -d /usr/bin/ \
    && rm -f ${TFLINT_FILE_NAME} ${TFLINT_CHECKSUM_FILE_NAME}.sig ${TFLINT_CHECKSUM_FILE_NAME} \
    && tflint --version
```
