### ISSUE TITLE
Enhancement: Add rule - disallow resource if resource module present

### ISSUE THREAD

**Issue by syedatifakhtar** [terraform-linters/tflint#615]
Use case-:

As a developer/Infra governance person in my project with a large terraform codebase i want to disallow or limit creation of resources readily available in my modules directory. One example of this is if i have created an S3 module which enforces TLS i want to check and make sure that developers are not creating their own S3 resources and should use the module everywhere in code. Same goes for other resources.

What value does this bring-: We can pre create resources based on security best practices followed in the project and enforce compliance. Add tflint to run as a pipeline step and fail every time someone tries to create something that already exists. I've seen this become a big problem in large terraform projects.

**Comment by wata727** [comment]
Hi @syedatifakhtar, thank you for sharing your use case.

I feel your request makes sense, but on the other hand, it seems difficult to achieve this as a generic linter rule. We have a plugin system to deal with organization-specific issues. Is this helpful?
https://github.com/terraform-linters/tflint-ruleset-template
