### ISSUE TITLE
Cannot start langserver

### ISSUE THREAD

**Issue by nitrocode** [terraform-linters/tflint#643]
Hi. Unsure of how to use this tool with tf12. I thought maybe running the `langserver` would help as I cannot get tflint to complain about missing tags.

```
✗ tflint --aws-region=us-west-2 --deep --module
... no output ...
```

This command hangs

```
✗ tflint --langserver
09:49:52 langserver.go:15: Starting language server...
```

## Version

```
✗ tflint --version
TFLint version 0.15.0
✗ terraform --version
Terraform v0.12.21
+ provider.aws v2.50.0
```

**Comment by wata727** [comment]
Probably it is not hang. That state is waiting for input from stdin.

**Comment by nitrocode** [comment]
Let's say this is more of a question than a bug then. Could you help me with this?

1. How does one detect missing tags for resources using tflint for terraform 0.12.x?
2. What's an example on how to use the langserver?

I looked for documentation and couldn't find any regarding the above

**Comment by wata727** [comment]
> How does one detect missing tags for resources using tflint for terraform 0.12.x?

Maybe another bug with this rule has affected it. See #644 
Could you try v0.15.1?

> What's an example on how to use the langserver?

The language server doesn't work alone. You need to use a language server client provided by an editor. If the editor can work against any language server, you can use it simply by following the editor settings.

In the case of VS Code, we are developing [a simple client](https://github.com/terraform-linters/vscode-tflint-lsc) for development, but it has not been released and is not intended for production use.
