### ISSUE TITLE
Auto update homebrew tflint

### ISSUE THREAD

**Issue by nitrocode** [terraform-linters/tflint#683]
Hi! I noticed that @chenrui333 has been manually making the PR to homebrew whenever tflint is upgraded which can be done using a command like this.

```bash
brew bump-formula-pr \
  --strict \
  --tag=GIT_TAG_GOES_HERE \
  --revision=GIT_COMMIT_GOES_HERE \
  tflint
```

Is there a way to automate this in github actions to run this immediately when a new release is published?

Reference: https://github.com/Homebrew/homebrew-core/pull/51990

**Comment by chenrui333** [comment]
yeah, that is good idea, I can take on this.

**Comment by chenrui333** [comment]
TBH, I was thinking about this this week.
