### ISSUE TITLE
Rule for Terraform version constraint

### ISSUE THREAD

**Issue by DWSR** [terraform-linters/tflint#711]
Hi there,

It would be helpful to have a rule that ensures that a Terraform version constraint is both present within a module and also specifies a specific minimum version (say `>=0.12.0`).

**Comment by mveitas** [comment]
This is something I'm interested in and will see what I can do about putting a pull request together

**Comment by bendrucker** [comment]
This was added in https://github.com/terraform-linters/tflint/pull/725, thanks!
