### ISSUE TITLE
enable all rules

### ISSUE THREAD

**Issue by y0y0z** [terraform-linters/tflint#712]
looking at [aws rules](https://github.com/terraform-linters/tflint/tree/master/rules/awsrules/models) and reading the [rules documentation](https://github.com/terraform-linters/tflint/tree/master/docs/rules), only some of the rules are enabled by default.

i tried to consult the [configuration guide](https://github.com/terraform-linters/tflint/blob/master/docs/guides/config.md), where it specifies how to enable or disable a rule
```hcl
rule "aws_instance_invalid_type" {
  enabled = false
}
```

but how can i enable all rules (aws specifically), which are not enabled by default, without listing each and every one of them?

**UPDATE:**
executing tflint in [debugging mode](https://github.com/terraform-linters/tflint#debugging), it prints
```shell
10:27:37 provider.go:107: [INFO]   784 rules enabled
```
does it mean that all the rules are enabled by default?

**Comment by CubicNitrous** [comment]
I am wondering this as well

**Comment by wata727** [comment]
As far as I know, all rules for AWS are enabled by default.

**Comment by y0y0z** [comment]
@wata727: so one needs to only disable modules when they not needed?

**Comment by wata727** [comment]
Sorry, I don't seem to understand the intent of your question.
Are you talking about disabling module inspection?
https://github.com/terraform-linters/tflint/blob/master/docs/guides/advanced.md#module-inspection

**Comment by y0y0z** [comment]
@wata727: never mind, got it! thank you :)
