### ISSUE TITLE
tflint passes this complete noob's code

### ISSUE THREAD

**Issue by gilescope** [terraform-linters/tflint#718]
As a tf noob it would be great if this could be pointed out as not being good:

provider "aws" {
  region = "eu-west-2"

  resource "aws_instance" "machine1" {
    ami           = "ami-098bb5d92c8886ca1"
    instance_type = "t2.micro"
  }
}

At the moment it say's its fine but I think putting a resource in a provider actually doesn't do anything and noob is left scrating head trying to figure out why tf plan says nothing to do.

**Comment by bendrucker** [comment]
Hey, can you check if `terraform validate` catches this? Quite surprised that Terraform doesn't complain about how that configuration violates the provider schema. TFLint does not interact with providers. Nested blocks in Terraform don't contain labels, except for `dynamic ""`, as far I know. But if not for that, TFLint would not be able to guarantee that this isn't a legitimate part of the provider configuration.

**Comment by bendrucker** [comment]
Happy to reopen if you can provide more info and we think TFLint can readily resolve this. Preferably Terraform itself would reject this kind of structural error and I still suspect it would.
