### ISSUE TITLE
Rule aws_dynamodb_table_invalid_stream_view_type doesn't accept empty string when stream is disabled

### ISSUE THREAD

**Issue by oben59** [terraform-linters/tflint#723]
As explained in this AWS provider issue: https://github.com/terraform-providers/terraform-provider-aws/issues/1134
We need to be able to pass empty string ("") as stream_view_type to the aws_dynamodb_table when stream_enabled is false, it is the input the AWS API expects, I got the described error with different inputs with the stream disabled.

Right now, tflint only allows the valid non empty values and returns an error message:
"" is an invalid value as stream_view_type (aws_dynamodb_table_invalid_stream_view_type)

**Comment by wata727** [comment]
Thank you for opening this issue. This bug is fixed in v0.15.5.
