### ISSUE TITLE
Fails to find file in root directory from a module

### ISSUE THREAD

**Issue by doublefelix7** [terraform-linters/tflint#733]
I have a resource defined inside a module called "iam", like so:

```
resource "aws_iam_role" "lambda_role" {
  name        = "LambdaRole"
  description = "Lambda role"
  path        = var.path
  tags        = var.tags
  assume_role_policy = templatefile("${path.root}/templates/assume_role_policy.tmpl",
    {
      aws_service = "lambda"
    }
  )
}
```
where the `templates` folder is inside the root module.
and when I run `tflint --modules`, I get this:
```
Error in function call: Call to function "templatefile" failed:
no file exists at iam/templates/assume_role_policy.tmpl.
```

but when I execute a terraform plan, it works fine. Is it not able to evaluate the `${path.root}`?

**Comment by wata727** [comment]
`path.root` seems to be evaluated as "iam". Could you tell us a little more concrete situation?

1. Where did you run `tflint --module`?
2. Where did you run `terraform plan`?
3. Please tell me the tree structure of the target module, root module and templates directory.

**Comment by doublefelix7** [comment]
I ran tflint from the root module. It's the same spot where I ran `terraform plan`. 

Here is my directory structure. This is from the root module.

```
.
├── iam
│   ├── main.tf
│   ├── outputs.tf
│   └── variables.tf
├── main.tf
├── templates
│   └── assume_role_policy.tmpl
└── variables.tf
```

**Comment by wata727** [comment]
Thanks, @doublefelix7. Identified this problem.

Probably, TFLint seems to have a different `path.root` result from Terraform because it rebuilds a child module as a root module. The following is a minimal example:

**main.tf**
```hcl
provider "aws" {
  region = "us-east-1"
}

module "ec2" {
  source = "./module"

  suffix = "t2.micro"
}
```

**module/ec2.tf**
```hcl
variable "suffix" {}

resource "aws_instance" "foo" {
  ami = "ami-12345678"
  instance_type = "${path.root}/${var.suffix}"
}
```

**Terraform output**
```
  + resource "aws_instance" "foo" {
      + ami                          = "ami-12345678"
      + arn                          = (known after apply)
      + associate_public_ip_address  = (known after apply)
      + availability_zone            = (known after apply)
      + cpu_core_count               = (known after apply)
      + cpu_threads_per_core         = (known after apply)
      + get_password_data            = false
      + host_id                      = (known after apply)
      + id                           = (known after apply)
      + instance_state               = (known after apply)
      + instance_type                = "./t2.micro"
```

**TFLint output**
```
Error: "module/t2.micro" is an invalid value as instance_type (aws_instance_invalid_type)

  on main.tf line 8:
   8:   suffix = "t2.micro"

Callers:
   main.tf:8,12-22
   module/ec2.tf:5,19-47
```

Until this bug is fixed, as a workaround, please disable the module inspection or set the corresponding module to `ignore_module`.
https://github.com/terraform-linters/tflint/blob/v0.15.5/docs/guides/config.md#ignore_module
