### ISSUE TITLE
TFLint crashed

### ISSUE THREAD

**Issue by larstobi** [terraform-linters/tflint#760]
~/.tflint.hcl exists and is empty.

 $ TFLINT_LOG=debug tflint  --enable-rule=aws_resource_missing_tags
09:30:21 config.go:90: [INFO] Load config: .tflint.hcl
09:30:21 config.go:267: [DEBUG] Config loaded
09:30:21 config.go:268: [DEBUG]   Module: false
09:30:21 config.go:269: [DEBUG]   DeepCheck: false
09:30:21 config.go:270: [DEBUG]   Force: false
09:30:21 config.go:271: [DEBUG]   IgnoreModules: map[string]bool{}
09:30:21 config.go:272: [DEBUG]   Varfiles: []string{}
09:30:21 config.go:273: [DEBUG]   Variables: []string{}
09:30:21 config.go:274: [DEBUG]   Rules: map[string]*tflint.RuleConfig{}
09:30:21 config.go:275: [DEBUG]   Plugins: map[string]*tflint.PluginConfig{}
09:30:21 option.go:51: [DEBUG] CLI Options
09:30:21 option.go:52: [DEBUG]   Module: false
09:30:21 option.go:53: [DEBUG]   DeepCheck: false
09:30:21 option.go:54: [DEBUG]   Force: false
09:30:21 option.go:55: [DEBUG]   IgnoreModules: map[string]bool{}
09:30:21 option.go:56: [DEBUG]   EnableRules: []string{"aws_resource_missing_tags"}
09:30:21 option.go:57: [DEBUG]   DisableRules: []string(nil)
09:30:21 option.go:58: [DEBUG]   Varfiles: []string{}
09:30:21 option.go:59: [DEBUG]   Variables: []string{}
09:30:21 loader.go:55: [INFO] Initialize new loader
09:30:21 loader.go:80: [INFO] Load configurations under .
09:30:21 loader.go:88: [INFO] Module inspection is disabled. Building a root module without children...
09:30:21 loader.go:140: [INFO] Load values files
09:30:21 runner.go:50: [INFO] Initialize new runner for root
09:30:21 terraform.go:96: [INFO] TF_VAR_* environment variable found: key=TF_VAR_github_personal_access_token
09:30:21 provider.go:83: [INFO] Prepare rules
09:30:21 provider.go:99: [DEBUG] `aws_resource_missing_tags` is enabled
09:30:21 provider.go:110: [INFO]   768 rules enabled
Panic: runtime error: invalid memory address or nil pointer dereference
 -> 0: main.main.func1: /main.go(30)
 -> 1: runtime.gopanic: /panic.go(969)
 -> 2: runtime.panicmem: /panic.go(212)
 -> 3: runtime.sigpanic: /signal_unix.go(695)
 -> 4: github.com/hashicorp/hcl/v2/gohcl.decodeBodyToStruct: /decode.go(60)
 -> 5: github.com/hashicorp/hcl/v2/gohcl.decodeBodyToValue: /decode.go(43)
 -> 6: github.com/hashicorp/hcl/v2/gohcl.DecodeBody: /decode.go(36)
 -> 7: github.com/terraform-linters/tflint/tflint.(*Runner).DecodeRuleConfig: /runner.go(337)
 -> 8: github.com/terraform-linters/tflint/rules/awsrules.(*AwsResourceMissingTagsRule).Check: /aws_resource_missing_tags.go(312)
 -> 9: github.com/terraform-linters/tflint/cmd.(*CLI).inspect: /inspect.go(57)
 -> 10: github.com/terraform-linters/tflint/cmd.(*CLI).Run: /cli.go(82)
 -> 11: main.main: /main.go(43)
 -> 12: runtime.main: /proc.go(203)
 -> 13: runtime.goexit: /asm_amd64.s(1373)

TFLint crashed... :(
Please attach an output log, describe the situation and version that occurred and post an issue to https://github.com/terraform-linters/tflint/issues

main.tf
```hcl
output "example" {
  value = "hello"
}
```

## Version

TFLint v0.16.0
Terraform v0.12.24

**Comment by wata727** [comment]
Thank you for reporting. This seems to be a bug because it doesn't consider enabling rules with required options with the `--enable-rule` flag.

The workaround is to enable the rule in `.tflint.hcl` instead of the command line flag. I plan to fix this bug in the next version and change it so that it will be an error even if it is enabled if the required option is missing.
