### ISSUE TITLE
Support for Terraform 0.13

### ISSUE THREAD

**Issue by mveitas** [terraform-linters/tflint#770]
Beta releases of Terraform 0.13 are going to start shipping on June 3: https://github.com/hashicorp/terraform/issues/25016

**Comment by wata727** [comment]
In my understanding,  the changes don't have a big impact on TFLint, but it seems good to start investigating early when the beta is released.

**Comment by bendrucker** [comment]
It's possible that module instances could have some impact, but otherwise agreed that the work should be minimal. Since Terraform versions are for the CLI and don't apply to the go packages, there's always some possibility of breakage. Bits of 0.13 have been landing in master for a few months now so we don't have to wait for actual beta releases to try it out either.

**Comment by danieldreier** [comment]
Beta 1 was just released today!

**Comment by bendrucker** [comment]
👋 Hey Daniel, eager to try it out! Will open a draft PR upgrading TFLint soon.

**Comment by bendrucker** [comment]
Yeah that’s expected. TFLint consumes Terraform as a library. The dependency will need to be updated to support new features.

That’s not to say everything will necessarily work straight away, but simple schema errors like you posted should be immediately addressable. 

I’ll spend some time later today getting a branch and draft PR open to track this, including build instructions.

**Comment by gmazelier** [comment]
Great!

**Comment by bendrucker** [comment]
Opened https://github.com/terraform-linters/tflint/pull/804 which will track the effort to update for 0.13. Still some additional work required to handle the fact that modules can have multiple instances. Some more guidance on the 0.13 process, copied from the PR:

<hr>

For specific issues (crashes, errors, etc.), please open a new issue and reference that you are testing with 0.13. Please include example configuration.

For general discussion, please comment on the main issue.

<hr>

This will apply once #804 is passing tests. For now please sit tight, but PRs are welcome!

**Comment by bendrucker** [comment]
#804 now build/passes tests, please check that out and build locally if you're trying out Terraform 0.13. Now would be a good time to start reporting any unexpected errors for valid configurations (as new issues). As described in #804, TFLint is still not aware of multiple module instances. It won't try to evaluate the `for_each` or `count` attributes in module calls which means any attribute using `each.*` or `count.*` is unknown. Resources treat these values similarly and don't statically analyze for_each/count except to detect when a resource is skipped altogether.

**Comment by wata727** [comment]
#804 was merged. It will be included in v0.19.
