### ISSUE TITLE
Expression evaluation errors cannot be suppressed by annotations

### ISSUE THREAD

**Issue by sergei-ivanov** [terraform-linters/tflint#778]
We have variables of complex types, which may be null by default. The resources are created only when variable value is not null, and resource properties are populated from the fields of the value.

To illustrate, we have a module with the following variable and resource:

```hcl
variable "maintenance_cron_start" {
  description = "SSM compatible cron statement to schedule the restart."
  type = object({
    schedule          = string
    schedule_timezone = string
  })
  default = null
}

resource "aws_ssm_maintenance_window" "start" {
  count = var.maintenance_cron_start != null ? 1 : 0

  schedule                   = var.maintenance_cron_start.schedule
  schedule_timezone          = var.maintenance_cron_start.schedule_timezone
  # ... rest of the properties
}
```

The calling module can optionally activate the maintenance window by assigning a map to the variable, for example:

```hcl
module "ssm" {
  # ...
  maintenance_cron_start               = {
    schedule          = "cron(58 5 ? * MON-FRI *)"
    schedule_timezone = "Europe/London"
  }
}
```

Unfortunately, TFlint cannot process such configuration and it produces the following error:

```
Failed to check `aws_ssm_maintenance_window_invalid_schedule` rule. An error occurred:

Error: Failed to eval an expression in ssm.tf:214; Attempt to get attribute from null value: This value is null, so it does not have any attributes.
```

Obviously TFlint does not realise that the resource creation is conditional on the variable being non-null (which is something that is only fully resolved at plan time).

I tried placing `# tflint-ignore: aws_ssm_maintenance_window_invalid_schedule` annotation on the offending line and on the line above, but it did not have any effect: the error was still reported.

The only way around that worked was creating a `tflint.tfvars` file, populating the mock values for the variables, and passing that tfvars file to TFlint. If I set up invalid values in tfvars, they are correctly reported by the rule, and can be suppressed by annotation as well.

So I guess the main question is: should annotations suppress expression evaluation errors as well? If the answer is "yes", then there's a bug. If the answer is "no", then there's a gap in the documentation.

## Version

TFLint v0.16.1
Terraform v0.12.26

**Comment by wata727** [comment]
Hi @sergei-ivanov, thank you for sharing your use-case.

> should annotations suppress expression evaluation errors as well?

No. Initially, annotations were meant to ignore reported issues, not designed to ignore errors.

There is no way to ignore the evaluation error because I think the situation where the error occurs is obviously a broken configuration or that is a bug in TFLint.

I didn't know the specification that expression of each attribute is not evaluated when `count` is 0. So, I think TFLint should evaluate the value of count as well, and only evaluate the expression if it is non-zero.

**Comment by bendrucker** [comment]
This would apply to for_each as well. 

The value don’t have to be static, they can reference data sources. Static evaluation handles simple cases but not all. 

I think an annotation that allows eval errors to be ignored for a whole resource is the only general solution here. It could be limited to use with count/for_each, even only with unknown values. Not sure that’s necessary though. 

Static evaluation could handle most situations and the annotation would be a fallback.

**Comment by wata727** [comment]
I think there are several ways, but in my opinion, I would like to choose a way to exclude the resource from the inspection if `count` or `for_each` values are not evaluable. This is because I prefer false negatives to false positives.

**Comment by sergei-ivanov** [comment]
I agree that statically calculating `count` and `for_each` may not always be possible. Moreover, if TFLint wanted to properly take `count` and `for_each` into account, it would have to emulate iteration and check that the resource attributes were valid for each value of the index or iterator. That may be challenging to implement.

So in a way I am happy with my current approach of supplying TFLint-specific `tflint.tfvars` file, but I wonder if there are some rare cases where we shall still need to suppress evaluation errors.

**Comment by wata727** [comment]
TFLint is designed to skip evaluations when Terraform's behavior cannot be accurately emulated. For instance, we can't properly expand `for_each` and dynamic block, as you say.  However, if the `each.*` computed by it is contained in the expression being inspected, we can avoid it correctly.

Except for this example, I believe there is no pattern that cannot avoid evaluation errors, but we may need to consider suppressing errors with annotations if we faced an uncontrollable issue.
