### ISSUE TITLE
Feature: Ability to set plugin directory

### ISSUE THREAD

**Issue by jpreese** [terraform-linters/tflint#781]
TL;DR It would be nice to be able to specify where the plugins are stored. 💯

**Comment by jpreese** [comment]
My immediate use case is using a plugin inside of a build container in a CI pipeline. I have a Dockerfile that contains both tflint and the azurerm plugin,.

Unfortunately, at least with Azure DevOps, build containers in CI are always run under the user `azureuser_azpcontainer`. This means that my Dockerfile also has to put the plugin in this path, for that user. It's not a _huge_ deal, but it feels slightly off to create a specific user. With our Terraform plugins, we just always put them in `/opt` and set the TF_PLUGIN_CACHE_DIR variable.

To answer your last question, yes, I was thinking the typical approaches: environment variable, something we can set inside of `.tflint.hcl`, and/or a flag on `tflint` itself.

**Comment by wata727** [comment]
Thank you for the explanation. It makes sense. Probably it would be good to be able to change it with an environment variable like `TFLINT_PLUGIN_DIR`.
