### ISSUE TITLE
Feature request: junit output format

### ISSUE THREAD

**Issue by clar-cmp** [terraform-linters/tflint#786]
CircleCI uses this format for test results, and it would be very helpful to show lints on CI.

**Comment by bendrucker** [comment]
I might take a look at this one since I use CircleCI at work. If you wanted to take a stab, the relevant package is here:

https://github.com/terraform-linters/tflint/tree/master/formatter

**Comment by bendrucker** [comment]
Some relevant references here:

* Go types we could copy/use https://github.com/jstemmer/go-junit-report/blob/master/formatter/formatter.go#L23-L41
* Example output from ESLint: https://eslint.org/docs/user-guide/formatters/#junit
