### ISSUE TITLE
Feature: add Oracle Cloud (OCI) support

### ISSUE THREAD

**Issue by sycured** [terraform-linters/tflint#808]
It'll be good to have Oracle Cloud (OCI) support

**Comment by wata727** [comment]
Thank you for opening this issue.

I would like to provide support for new providers through plugins.
If you're interested, you can write a plugin. See https://github.com/terraform-linters/tflint-plugin-sdk

**Comment by yashd** [comment]
@wata727  Can you let me know what is the provider for adding new plugin for OCI. Currently I have the code for OCI plugin in my personal repository(https://github.com/yashd/tflint-ruleset-oci)

**Comment by wata727** [comment]
Plugins are independent binaries that users can install to add provider support.

**Comment by wata727** [comment]
Close this because OCI support is now available with [tflint-ruleset-oci](https://github.com/yashd/tflint-ruleset-oci) plugin.

**Comment by ireshdudeja** [comment]
[tflint-ruleset-oci](https://github.com/yashd/tflint-ruleset-oci) is not available.

**Comment by winston0410** [comment]
Just realized that the plugin is not available as well. should this ticket be reopened again?

**Comment by sadiq250691** [comment]
Can some one help me to get OCI RULE SET and plugin for TFLINT

**Comment by kcbraunschweig** [comment]
can this be reopened? what happened to tflint-ruleset-oci?

**Comment by alant94** [comment]
> Close this because OCI support is now available with [tflint-ruleset-oci](https://github.com/yashd/tflint-ruleset-oci) plugin.

@wata727 the plugin is not available, could you please reopen this issue?
