### ISSUE TITLE
Doubt and Suggestion required

### ISSUE THREAD

**Issue by vikaskoppineedi** [terraform-linters/tflint#816]
Hi Team, 

I am trying to make tflint work in our Jenkins Pipelines.  We are using Terraform v12. 

![image](https://user-images.githubusercontent.com/16710275/85298093-44611400-b469-11ea-8fd3-b4da1fbde9a6.png)

The contents of the .tflint.hcl file are here. 
![image](https://user-images.githubusercontent.com/16710275/85298187-63f83c80-b469-11ea-9f85-5a7d07099fd1.png)

And here is how my main.tf block looks like. It is like this because we use Terragrunt. 
![image](https://user-images.githubusercontent.com/16710275/85298348-95710800-b469-11ea-9acd-c6d92c53984e.png)

Can someone please help me with the error and what am i doing wrong?

**Comment by wata727** [comment]
Looks like there is a syntax error in `.tflint.hcl`. The closing brace on line 11 is invalid.
It seems necessary to rewrite as follows:

```hcl
config {
  module = true
  deep_check = true
  force = false

  aws_credentials = {
    profile                 = "nano-non-prod"
    region                  = "us-east-1"
    shared_credentials_file = "~/.aws/credentials"
  }

  varfile = ["terraform.tfvars"]
}

rule "aws_instance_invalid_type" {
  enabled = true
}
```

**Comment by vikaskoppineedi** [comment]
Ok @wata727 Thanks, I was able to proceed further, but I am not able to see what the issue could be, 

I tried on my local and also through my CI, invoking tflint does nothing. 

![image](https://user-images.githubusercontent.com/16710275/85325406-31623a00-b491-11ea-9f41-be92ae136485.png)


On my CI Server, 
![image](https://user-images.githubusercontent.com/16710275/85325547-6f5f5e00-b491-11ea-8ada-e3a8e99ae08c.png)

Here is my CI COnfiguration. 
![image](https://user-images.githubusercontent.com/16710275/85325612-8736e200-b491-11ea-9726-c653fdc86374.png)

Any help is appreciated. If this is not the right place to ask this, please close the ticket.

**Comment by bendrucker** [comment]
That error is related to AWS credentials. Hard to say what's wrong without full visibility into your configuration. Perhaps there are simply no credentials in the file you've referenced, the profile is missing, or something else. 

In any case, doesn't seem to be any specific TFLint issue here. Feel free to continue to post questions/ideas and we can give you some pointers, but can't delve deep into proprietary config.
