### ISSUE TITLE
Add Custom  rule to tflint

### ISSUE THREAD

**Issue by TechGirl-3** [terraform-linters/tflint#832]
Hi,

Is there a document available to add custom rules to tflint.

Thanks in Advance.

**Comment by bendrucker** [comment]
Yes, some initial instructions are available here:

https://github.com/terraform-linters/tflint/blob/master/docs/DEVELOPING.md

Your options for custom rules are either plugins or submitting rules for inclusion in the core library. Happy to help with PRs.
