### ISSUE TITLE
terraform_required_providers errs with multiple copies of the same provider

### ISSUE THREAD

**Issue by nijave** [terraform-linters/tflint#839]
(currently?) Terraform won't let you use multiple versions of the same provider for a project so the second provider is implicitly pinned to the version of the first provider. We have some instances of this where a Terraform project touches multiple AWS regions (like RDS replicas) and I think it's not necessarily desirable to pin the version multiple times since the first pinned version is always used anyway

If I pin to 2.64.0 & 2.65.0, respectively, `No provider "aws" plugins meet the constraint "2.64.0,2.65.0".`

```hcl
provider "aws" {
  assume_role {
    role_arn = "arn:aws:iam::123:role/admin"
  }

  version = "~> 2.0"
  region  = "us-east-2"ee

provider "aws" {
  assume_role {
    role_arn = "arn:aws:iam::123:role/admin"
  }

  alias  = "useast1"
  region = "us-east-1"
}
```

## Version
TFLint v0.17.0
Terraform v0.12.25

Maybe it some cases it's desirable to major version pin one provider and minor version pin another so possibly this could be a configurable option but in most cases I don't think someone would want to duplicate version requirements

**Comment by bendrucker** [comment]
Don't quite understand the issue here. The one snippet of what looks like an error isn't coming from TFLint. Assuming the config you shared is complete, can we please get the full output?

**Comment by nijave** [comment]
> Don't quite understand the issue here. The one snippet of what looks like an error isn't coming from TFLint. Assuming the config you shared is complete, can we please get the full output?

The error message is in the issue title but here's the full output
```
$ tflint -c ../../../.tflint.hcl --module --deep
1 issue(s) found:

Warning: Provider "aws" should have a version constraint in required_providers (aws.useast1) (terraform_required_providers)

  on main.tf line 24:
  24: provider "aws" {

Reference: https://github.com/terraform-linters/tflint/blob/v0.17.0/docs/rules/terraform_required_providers.md
```

**Comment by bendrucker** [comment]
Ah, I get it. Why not use the `required_providers` block?

While it's possible to inspect other provider blocks of the same name looking for a version, I'm hesitant to try to suppress this error. It is valid for each provider block to specify its own semver range, as long as there's intersection among all the ranges for a given provider name. 

It creates duplication if your intent is to have a single range across all providers, but you have `required_providers` for that.

**Comment by nijave** [comment]
> Ah, I get it. Why not use the `required_providers` block?
> 
> While it's possible to inspect other provider blocks of the same name looking for a version, I'm hesitant to try to suppress this error. It is valid for each provider block to specify its own semver range, as long as there's intersection among all the ranges for a given provider name.
> 
> It creates duplication if your intent is to have a single range across all providers, but you have `required_providers` for that.

tbh didn't realize you could pin versions so I guess I'm just more confused by the wording of the error since it errors on the one without a pinned version and states to use "required_providers" even tho the first one passes without that since it's pinned in the provider block

i.e.
```
$ cat main.tf 
provider "aws" {
  version = "2.65.0"
}

provider "aws" {
  alias = "aws2"
}

$ tflint --enable-rule=terraform_required_providers
1 issue(s) found:

Warning: Provider "aws" should have a version constraint in required_providers (aws.aws2) (terraform_required_providers)

  on main.tf line 5:
   5: provider "aws" {

Reference: https://github.com/terraform-linters/tflint/blob/v0.17.0/docs/rules/terraform_required_providers.md
```

**Comment by bendrucker** [comment]
Correct. The preferred way to restrict versions in 0.12+ is with `required_providers`, which restricts a provider by name. The intent of the rule is to ensure provider versions are restricted, so it accepts providers that set a `version` even if they are not included in `required_versions`:

https://github.com/terraform-linters/tflint/blob/master/rules/terraformrules/terraform_required_providers.go#L44

I think the best option for clarity would be to emit warnings for `version` with a recommendation to move to `required_providers`. This would mean you'd get a slightly different warning for both provider blocks.
