### ISSUE TITLE
How to create a new custom rule

### ISSUE THREAD

**Issue by Neekoy** [terraform-linters/tflint#935]
Heya,

I went through the documentation a couple of times, but it goes over my head at the moment.

I need to create a linting rule, which would check if the variable `origin_ssl_protocols` contains any of the following entries:

origin_ssl_protocols   = ["SSLv3", "TLSv1", "TLSv1.1", "TLSv1.2"]

If it contains any entries different than the above, the linting should fail.

Any help is appreciated, thanks in advance.

**Comment by wata727** [comment]
Hi @Neekoy, [tflint-ruleset-template](https://github.com/terraform-linters/tflint-ruleset-template) will help you create a plugin. Please take a look.
