### ISSUE TITLE
How to evaluate attribute inside inner block

### ISSUE THREAD

**Issue by KyungUnChoi** [terraform-linters/tflint#936]
```hcl
resource "google_container_cluster" "private" {	
  name             = "my-cluster"
  workload_identity_config {
       identity_namespace = "someprojectid.svc.id.goog"
  }
}
```

I need to get the string value "someprojectid.svc.id.goog" in the Check()function.
What is the proper way to do it?

So far in Check() function, 
```go
return runner.WalkResourceBlocks(r.resourceType, r.blockName,
		func(block *hcl.Block) error {
			var attributes, _ = block.Body.JustAttributes()
			var attribute = attributes[r.attributeName]
			err := runner.EvaluateExpr(attribute.Expr, &givenValue)
			return r.ensureNoError(err, givenValue, r.attributeName, attribute, runner)
		},
	) 
```

Where

```go
r.resourceType = google_container_cluster
r.blockName = workload_identity_config 
r.attributeName = identity_namespace
```

This seems to work but only in the root module (main.tf), but it gets err if the terraform code is in an external module. 

It will be nice someone to show/point me to an example how it has done it.

Thanks
-Choi

**Comment by bendrucker** [comment]
How are you running TFLint, and what is the error related to modules?

**Comment by KyungUnChoi** [comment]
We append the rule (not plugin rule) to manualDefaultRules and build TFlint. (There is a long story why we do this way, but we have to do this way for now)

Here is the error message and the debug info for "attribute" variable. 
Notice the difference of the attribute.Expr debug info between external module and main.tf. 
I am not fully sure what is Expr for so running out of idea how to do this.

![image](https://user-images.githubusercontent.com/45368839/94776560-3d2f9780-03c2-11eb-9680-d8bf3f2bed25.png)
![image](https://user-images.githubusercontent.com/45368839/94776748-939cd600-03c2-11eb-92e4-413421ce249e.png)

This is the debug info with running against main.tf without an external module
When the terraform code is in main.tf (root module), attribute.Expr seems to be evaluable.
![image](https://user-images.githubusercontent.com/45368839/94777216-63096c00-03c3-11eb-9bac-f3dc0ce7f49b.png)

**Comment by bendrucker** [comment]
We'll need runnable code to look into this further. The expectation is that you'll write a rule set plugin. If you're building a custom version of TFLint itself we'll be less able/inclined to help since that's not officially supported. Also FWIW avoid `JustAttributes` and always use a partial schema to parse pieces of HCL documents/fragments.

**Comment by KyungUnChoi** [comment]
Hi, 
I understand that it is difficult support in my case.
So I have made fork the tflint and add the gcprules directory and the main.tf file to run debug.
https://github.com/KyungUnChoi/tflint
you will be able to run the test and and debug via vscode after running terraform init.

So far my troubleshooting lead me to the conclusion. Using a local variable with a conditional logic in the terraform module causes the issue.
.terraform/modules/gke/modules/beta-private-cluster/cluster.tf
***
  dynamic "workload_identity_config" {
    for_each = local.cluster_workload_identity_config

    content {
      identity_namespace = workload_identity_config.value.identity_namespace
    }
  }
***
I am not sure even it is possible to evaluate the final value or not in tflint.
I appreciate that if you could take a look at the issue. 

By the way, do you have a code snippet/example using a partial schema?
I am not sure that I was using it correctly. I had encountered a problem to use it before.
Thank for your response so far. 

Regards, 
-Choi

**Comment by bendrucker** [comment]
Yes, you can see partial schema examples here:

https://github.com/terraform-linters/tflint/search?q=PartialContent

The HCL package will parse the attributes/blocks you specify, while leaving the remaining content behind. Helps ensure better errors/avoid panics in case the attribute is missing. 

Appreciate the repro, this definitely seems likely:

> Using a local variable with a conditional logic in the terraform module causes the issue.

See #571 regarding that, at the moment TFLint isn't able to evaluate any `local` references. It can handle variables when supplied by `--var` or `--modules`.

**Comment by KyungUnChoi** [comment]
Thank, it was big help. 
Good to know the current limitation on evaluation. 

Thank you for the project and support.
