### ISSUE TITLE
AWS Gateway Load Balancer Support

### ISSUE THREAD

**Issue by bflad** [terraform-linters/tflint#975]
## Version

```
0.20.3
```

## Description

AWS recently announced support for a new type of Elastic Load Balancing solution, Gateway Load Balancers. Upstream support for this was released in AWS Go SDK version 1.35.25 and Terraform AWS Provider version 3.15.0.

The following two rules are now out of date for this support:

```
2 issue(s) found:

Error: "gateway" is an invalid value as load_balancer_type (aws_lb_invalid_load_balancer_type)

  on /tmp/tmp.dlbkTdYWjQ/main.tf line 2:
   2:   load_balancer_type = "gateway"

Error: "GENEVE" is an invalid value as protocol (aws_lb_target_group_invalid_protocol)

  on /tmp/tmp.dlbkTdYWjQ/main.tf line 13:
  13:   protocol = "GENEVE"
```

## References

* https://aws.amazon.com/elasticloadbalancing/gateway-load-balancer/
* https://github.com/aws/aws-sdk-go/releases/tag/v1.35.25
* https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.15.0

**Comment by bendrucker** [comment]
Thanks Brian! #976 will fill this.
