### ISSUE TITLE
[Question] What makes tflint OS dependent binary?

### ISSUE THREAD

**Issue by 1oglop1** [terraform-linters/tflint#990]
Hi, I'm wondering what makes `tflint` binary OS dependent?

I'm playing around with docker images of `terraform`, `terraform-docs` and `tflint`

and for `terraform` and `terraform-docs` I can copy the binary from their respective docker images based on `alpine:3.12`

into my image based on `debian-buster` and run the binary without any problem.

When I try the same with `tflint` it gives me an error `bash: ./tflint: cannot execute binary file`.  (binary works if transfered between different alpine containers though)

I'm mainly asking out of curiosity to learn more about tflint and Go.

Thank you.

**Comment by bendrucker** [comment]
Hmm, interesting. Go builds binaries for a specific operating system and processor architecture specified at build time. These binaries will only run on the specified OS/arch combo, and give an error similar to the one you shared when run on a different one. Things that differ across OSes are more user-facing (e.g. OS-specific switching in  `filepath`, `net`) whereas processor architecture is lower level. More background on that here:

https://www.digitalocean.com/community/tutorials/building-go-applications-for-different-operating-systems-and-architectures

In this case you'll be dealing with `linux/amd64` for both Debian and Alpine. But you might see something similar trying to run a Mac binary.

Then there's the possibility that binaries use dynamic linking and therefore depend on the host environment. That's most often the case when linking to C programs that use dynamic linking:

https://stackoverflow.com/questions/44606374/in-what-cases-are-go-binaries-dynamically-linked

However, TFLint should be built without any dynamic deps:

https://github.com/terraform-linters/tflint/blob/master/.goreleaser.yml#L4

So in this case I'm not entirely sure what the compatibility issue is. If `terraform` and `terraform-docs` can manage it it should be possible to make this work for TFLint too.

**Comment by 1oglop1** [comment]
Thanks, this was interesting. I've learned a lot :)
