### ISSUE TITLE
0.21.0 Need to update version for -v output

### ISSUE THREAD

**Issue by cemckenzie** [terraform-linters/tflint#997]
## 0.21.0: Need to update version for -v output

The command line shows an older version:

% tflint -v
% TFLint version 0.16.2

I am using macOS.

## Version

TFLint v0.21.0
Terraform v0.13.5

**Comment by bendrucker** [comment]
I was unable to reproduce this, seems like it's an issue with your local setup and that you are indeed running 0.16.2 in the example output.

Running:

```sh
curl https://github.com/terraform-linters/tflint/releases/download/v0.21.0/tflint_darwin_amd64.zip \
  --silent --location --output tflint.zip \
  && unzip ./tflint.zip \
  && ./tflint -v
```

Returns:

```
Archive:  ./tflint.zip
  inflating: tflint
TFLint version 0.21.0
```

The version comes from here, it's a constant value:

https://github.com/terraform-linters/tflint/blob/83fd42aaec41d709e8b55a922418907abaa274b0/tflint/meta.go#L5-L6
